name: CI/CD Node Docker to Azure

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkou code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t guilhermesousacosta/hello-azure-app:latest .
          docker build -t guilhermesousacosta/hello-azure-app:${{ github.sha }} .

      - name: Docker push
        run: |
          docker push guilhermesousacosta/hello-azure-app:latest
          docker push guilhermesousacosta/hello-azure-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: hello-azure-app
          images: guilhermesousacosta/hello-azure-app:latest
